version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    env_file:
      - ./app.env
    ports:
      - '6000:27017'
    volumes:
      - mongodb:/data/db

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redisDB:/data

  goapp:
    build:
      context: .  
      dockerfile: Dockerfile  
    container_name: goapp
    restart: always
    ports:
      - '8080:8080'  
    depends_on:
      - mongodb
      - redis

volumes:
  mongodb:
  redisDB: